name: tasas_eltoque
description: App para consultar tasas de cambio de elTOQUE.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP
  dio: ^5.7.0

  # Estado local / caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # State management
  flutter_bloc: ^9.1.1
  bloc: ^9.1.5

  # Iconos
  # flutter_svg: ^2.0.4
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4

  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/iconos/
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/iconos/icono.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/iconos/icono.png"

